[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38','py39','py310','py311']
include = '\.pyi?$'
exclude = '''
/(
  \.toml
  |\.sh
  |\.git
  |\.ini
  |Dockerfile
  |Jenkinfile
)/
'''