FROM python:3.13.0a3-slim

RUN mkdir /src
WORKDIR /src

RUN apt update -y
RUN apt install -y build-essential python3-pip

COPY . .

RUN pip3 install -r requirements.txt

ENV PYTHONUNBUFFERED=0

EXPOSE 5000
CMD ["python3", "-u", "main.py"]